# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Party-organizer' do
 
  use_frameworks!

  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'RealmSwift'
  pod 'PureLayout'


end
